# Generated by Django 4.0.5 on 2022-06-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_network_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
