# Generated by Django 4.0.5 on 2022-06-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_network_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(verbose_name='Ключ')),
                ('img', models.ImageField(upload_to='img/', verbose_name='Фото для категория')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создание')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('network', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Соц сеть',
                'verbose_name_plural': 'Соц сети',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Товар')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='img/', verbose_name='Фото Товара')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
